# Generated by Django 5.0 on 2023-12-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                ("city_id", models.IntegerField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "cities",
            },
        ),
        migrations.AddConstraint(
            model_name="cities",
            constraint=models.UniqueConstraint(
                fields=("city",), name="unique_city_name"
            ),
        ),
    ]
